/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-dim": "#dcdad6",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#d7c3b0",
        "on-tertiary-fixed": "#241a0e",
        "on-secondary-fixed-variant": "#2e4a5d",
        "surface-bright": "#fcf9f5",
        "surface-container-low": "#f6f3ef",
        "inverse-on-surface": "#f3f0ec",
        "secondary-fixed": "#c9e6fe",
        "surface-container-high": "#ebe8e4",
        "primary-fixed": "#beebe6",
        "surface-variant": "#e5e2de",
        "on-tertiary-container": "#fffbff",
        "tertiary-fixed": "#f4dfcb",
        "primary-container": "#527c78",
        "tertiary-container": "#827261",
        "on-secondary-container": "#4a667a",
        primary: "#39635f",
        secondary: "#466276",
        "surface-container": "#f0ede9",
        background: "#fcf9f5",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "secondary-container": "#c6e3fc",
        "secondary-fixed-dim": "#adcae2",
        outline: "#717878",
        "on-surface": "#1c1c19",
        "inverse-surface": "#31302e",
        "surface-tint": "#3c6662",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#e5e2de",
        error: "#ba1a1a",
        "on-secondary-fixed": "#001e2f",
        "on-primary-container": "#f3fffd",
        "on-primary-fixed": "#00201e",
        "on-error-container": "#93000a",
        "inverse-primary": "#a3cfca",
        "outline-variant": "#c1c8c7",
        tertiary: "#68594a",
        "on-primary-fixed-variant": "#234e4a",
        "on-tertiary-fixed-variant": "#524436",
        "error-container": "#ffdad6",
        surface: "#fcf9f5",
        "primary-fixed-dim": "#a3cfca",
        "on-background": "#1c1c19",
        "on-surface-variant": "#414848",
        "on-error": "#ffffff",
      },
      fontFamily: {
        headline: ["Noto Serif", "serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
